version: '3.8'
services:
  db:
    image: postgres:15.1-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
        - db_network
  
  web:
    ports:
      - "8000:8000"
    build:
      context: .
      args:
        TOKEN: ${GITHUB_TOKEN}
    depends_on:
      - db
    restart: always
    volumes:
      - ./data/web:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
      - WEB_FQDN=${WEB_FQDN}
      - WEB_PORT=${WEB_PORT}
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 