# Generated by Django 4.1 on 2022-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0002_alter_revticket_growth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revticket',
            name='growth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
