# Generated by Django 4.1 on 2022-09-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0003_alter_revticket_growth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revticket',
            name='growth',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
