# Generated by Django 4.1 on 2022-09-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0004_alter_revticket_growth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishticket',
            name='addtlMods',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
