# Generated by Django 4.1 on 2024-01-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231231_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='staff/images'),
        ),
    ]
